# Generated by Django 3.1 on 2020-08-08 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washroom',
            name='last',
        ),
        migrations.AddField(
            model_name='washroom',
            name='access',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AddField(
            model_name='washroom',
            name='diaper',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AddField(
            model_name='washroom',
            name='indoor',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AddField(
            model_name='washroom',
            name='opening_hours',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='washroom',
            name='type',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='washroom',
            name='water',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AddField(
            model_name='washroom',
            name='wheelchair',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AlterField(
            model_name='washroom',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='washroom',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='washroom',
            name='unisex',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=100)),
                ('washroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wee.washroom')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
