# Generated by Django 3.1 on 2020-08-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wee', '0002_auto_20200808_0048'),
    ]

    operations = [
    ]
