# Generated by Django 3.1 on 2020-08-08 01:17

from django.db import migrations
from django.contrib.auth.admin import User
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path
import random
DATA_FILENAME = 'data.json'
#https://realpython.com/location-based-app-with-geodjango-tutorial/

def load_data(apps, schema_editor):
    sample_id = 0
    Washroom = apps.get_model('wee', 'Washroom')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            sample_id = sample_id +1
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    access = 'False'
                    diaper = 'False'
                    wheelchair = 'False'
                    rating = round(random.uniform(0.0, 5.0),2)
                    water = 'False'
                    indoor = 'False'
                    id = obj.get('id',sample_id)
                    name = tags.get('name', 'Washroom')
                    opening_hours = tags.get('opening_hours', '')
                    unisex = tags.get('unisex', False)
                    type= tags.get('toilets:disposal','Type unknown')
                    if (tags.get('access')!='customer' or tags.get('access')=='no'):
                        access = "True"
                    if (tags.get('indoor')=="yes" or tags.get('indoor')=='building'):
                        indoor = "True"
                    if(tags.get('changing_table')=='yes' or tags.get('diaper')=='yes'):
                        diaper = "True"
                    if(tags.get('wheelchair')=='yes' or tags.get('toilets:wheelchair')=='yes'):
                        wheelchair = "True"
                    if(tags.get('drinking_water')=='yes' or tags.get('drinking_water')=='fountain'):
                        water = "True"
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(
                        f'POINT({longitude} {latitude})', srid=4326
                    )
                    Washroom(id=id,name=name,location=location, rating = rating, unisex=unisex,type=type, access=access, indoor=indoor, diaper=diaper, wheelchair=wheelchair, water=water,
                    	opening_hours = opening_hours).save()
            except KeyError:
                pass

def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'user1'
    superuser.email = 'admin@admin.net'
    superuser.set_password('user1')
    superuser.save()

class Migration(migrations.Migration):

    dependencies = [
        ('wee', '0003_auto_20200808_0114'),
    ]

    operations = [
    	migrations.RunPython(load_data),
        migrations.RunPython(create_superuser)
    ]
